# Generated by Django 3.1.5 on 2021-02-27 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=4096)),
                ('price', models.IntegerField(verbose_name='price of product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textPositive', models.TextField(max_length=4096)),
                ('textNegative', models.TextField(max_length=4096)),
                ('textSummary', models.TextField(max_length=4096)),
                ('username', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=40)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating of product from 1 to 5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('reviewLikes', models.IntegerField(verbose_name='the number of users who think the review is useful')),
                ('reviewDislikes', models.IntegerField(verbose_name='the number of users who think the review is useless')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('username', models.TextField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.review')),
            ],
        ),
    ]
