# Generated by Django 3.1.5 on 2021-03-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210323_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
