# Generated by Django 3.1.5 on 2021-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(default=-1, verbose_name='average rating'),
        ),
    ]
