# Generated by Django 3.1.5 on 2021-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='like = 1; dislike = -1'),
        ),
    ]
